In [32]:
import pandas as pd
import numpy as np

In [34]:
measurement_info = pd.read_excel(
    "download/measurement_template_filled.xlsx",
    header=0,
    skiprows=3,
    nrows=9,
    names=["id","description","value"],
    usecols=[0,1,2],
    dtype= {
            "id": np.int64,
            "description": str,
        }
)
measurement_info

   id   description                value
0   1            ID                 MST2
1   2         Datum  2023-01-22 00:00:00
2   3          Name               Muster
3   4       Vorname                  Max
4   5  Geburtsdatum  1996-01-10 00:00:00
5   6    Geschlecht                    M
6   7    Händigkeit                    R
7   8    Instrument              Violine

In [35]:
try:
    measurement_data = pd.read_excel(
        "download/measurement_template_filled.xlsx",
        header=0,
        skiprows=14,
        usecols=[0,1,2,5,6],
        names=["id","device","description","left","right"],
        dtype={
            "id": np.int64,
            "device": str,
            "description": str,
            "left": np.float64,
            "right": np.float64
        }
    )
except ValueError as e:
    print(e) 
measurement_data

,id,device,description,left,right
0,1,Handlabor,Handlänge,194.00,193.00
1,2,Handlabor,Handbreite,86.00,86.00
2,3,Handlabor,Handindex 2:1,0.44,0.44
3,4,Handlabor,Handgelenkbreite,58.00,58.00
4,5,Handlabor,Handrückenlänge,99.00,98.00
...,...,...,...,...,...
98,234,Handgelenk,"Abduktion ulnar + Flexion, 50 Ncm",NaN,NaN
99,235,Handgelenk,"Abduktion radial + Extension, 50 Ncm",NaN,NaN
100,236,Handgelenk,"Summe Abduktion + Extension / Flexion, 50 Ncm",NaN,NaN
101,237,Handgelenk,Extension aktiv,NaN,NaN
102,238,Handgelenk,Flexion aktiv,NaN,NaN

In [31]:
measurement_data\
    .melt(id_vars=['device','description'], var_name='hand', ignore_index=False)\
    .set_index(["hand"], append=True)

               device                                    description   value
id  hand
1   left    Handlabor                                      Handlänge  194.00
2   left    Handlabor                                     Handbreite   86.00
3   left    Handlabor                                  Handindex 2:1    0.44
4   left    Handlabor                               Handgelenkbreite   58.00
5   left    Handlabor                                Handrückenlänge   99.00
...               ...                                            ...     ...
234 right  Handgelenk              Abduktion ulnar + Flexion, 50 Ncm     NaN
235 right  Handgelenk           Abduktion radial + Extension, 50 Ncm     NaN
236 right  Handgelenk  Summe Abduktion + Extension / Flexion, 50 Ncm     NaN
237 right  Handgelenk                                Extension aktiv     NaN
238 right  Handgelenk                                  Flexion aktiv     NaN

[206 rows x 3 columns]